---
title: "HOMEWORK 4"
author: "Raul Rodriguez"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}

library(gridExtra)
library(ggplot2)

admissions_data <- read.csv('AdmissionPredict_202305.csv')

col_names <- c('TOEFL', 'GRE' ,'UGPA' ,'Univ_Rating' , 'SOP' , 'LOR')

create_plot <- function(name) {
  ggplot(admissions_data, aes_string(x = name, y = "Chance_of_Admit")) +
    geom_point() +
    labs(x = name, y = "Chance of Admit")
}

#a)
plots <- lapply(col_names, create_plot)
do.call(grid.arrange, c(plots, ncol = 3))

#b)
# I am able to identify a relationship  in TOEFL, GRE, UGPA, 
# CHANCE_OF_ADMIT, LOR, SOP, AND Univ_Rating. The type of relationship
# that i see is linear with an upward trend. 

#C)
model <- lm(Chance_of_Admit ~ TOEFL + GRE + UGPA + Univ_Rating + SOP + LOR, data = admissions_data)
model

#d)
# All terms are significant (p < 0.05) with the exception of UGPA. This means 
# That all values with the exception of UGPA contribute to the prediction of 
# Chance_of_Admit.

#e)
new_model <- lm(Chance_of_Admit ~ TOEFL + GRE + Univ_Rating + SOP + LOR, data = admissions_data)
new_model

#f)

range_values <- sapply(admissions_data[, c("TOEFL", "GRE", "Univ_Rating", "SOP", "LOR")], range)
range_values

#g) 

TOEFL_score <- 108
GRE_score <- 330
UGPA_score <- 7.8
Univ_Rating <- 4
SOP_score <- 3
LOR_score <- 4

new_student <- data.frame(TOEFL = TOEFL_score, GRE = GRE_score, UGPA = UGPA_score, Univ_Rating = Univ_Rating, SOP = SOP_score, LOR = LOR_score)

predicted_chance <- predict(new_model, newdata = new_student)

predicted_chance


```

```{r q, }

age = c(2,3,4,5,8,11,14,17,21,28,38,50,67,83)

 run.time = c(65,58,40,37,32,26,18,16,17,17,23,29,42,59)
 
 data <- data.frame(age = age, run_time = run.time)
 
 #a) 
 # The response variable (dependent) is the run time, 
 # as it depends on the age of the runner. Which would
 # make age the explanatory variable (independent)
 
 #b)
 ggplot(data = data, aes(x = age, y = run_time)) + 
   geom_point()
 
 # The relationship forms a u-shape. Meaning that the youngest and the oldest have the
 # highest running times. While the 'middle' group scores the lowest running times.
 
 #c)
 model <- lm(run.time ~ age + I(age^2), data = data)
 
 #d)
 test_person <- data.frame(age = 56)
 predicted_run_time <- predict(model, test_person = new_data)
 predicted_run_time <- predict(model, test_person = new_data)
 predicted_run_time
 
 #e)
 
 r_squared <- summary(model)$r.squared 
print('percentage: ')
r_squared * 100
 
 
```


